const nextWorkboxWebpackPlugin = require("next-workbox-webpack-plugin");

nextWorkboxWebpackPlugin({
    // must, see next.config.js below
    buildId,
    // optional, next.js dist path as compiling. most of cases you don't need to fix it.
    distDir: ".next",
    // optional, which version of workbox will be used in between 'local' or 'cdn'. 'local'
    // option will help you use copy of workbox libs in localhost.
    importWorkboxFrom: "local",
    // optional ,whether make a precache manifest of pages and chunks of Next.js app or not.
    precacheManifest: true,
    // optional, whether delete workbox path generated by the plugin.
    removeDir: true,
    // optional, path for generating sw files in build, `./static/workbox` is default
    swDestRoot: "./static/",
    // optional, path for serving sw files in build, `./static/workbox` is default
    swURLRoot: "/static",
    // optional, you can use workbox-build options. except swDest because of output location is fixed in 'static/workbox',
    ...WorkboxBuildOptions,
});